[package]
name = "turfrace"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.19.0"
clipper2-rust = "1.0.3"
earcutr = "0.5.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3"
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = [
    "Document",
    "Storage",
    "Window",
] }

[profile.release]
codegen-units = 1
lto = "thin"
opt-level = "s"
strip = true
