//! Public data model and limits for NPC behavior-laboratory artifacts.

use std::{collections::BTreeMap, fmt};

use serde::{Deserialize, Serialize};

use crate::match_game::{ComparableSnapshot, MatchSpec, SteeringCommand};

// Version 2 records explicit tactic transitions and tick-aligned trajectory
// samples. Version 1 artifacts used whole-run evidence and are intentionally
// not accepted by the verifier.
pub const LAB_FORMAT_VERSION: u32 = 2;
pub const LAB_SETUP_VERSION: u32 = 2;
pub const MAX_TICKS: u64 = 7_200;
pub const MAX_TRACE_RECORDS: usize = 512;
pub const MAX_TRAJECTORY_POINTS: usize = 2_048;

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum EncounterFixture {
    ReturnRace,
    Interception,
    BaitDisengagement,
    DistractedTerritory,
    LoopCapture,
    BridgeCapture,
}

impl EncounterFixture {
    pub const ALL: [Self; 6] = [
        Self::ReturnRace,
        Self::Interception,
        Self::BaitDisengagement,
        Self::DistractedTerritory,
        Self::LoopCapture,
        Self::BridgeCapture,
    ];

    pub const fn label(self) -> &'static str {
        match self {
            Self::ReturnRace => "return-race",
            Self::Interception => "interception",
            Self::BaitDisengagement => "bait-disengagement",
            Self::DistractedTerritory => "distracted-territory",
            Self::LoopCapture => "loop-capture",
            Self::BridgeCapture => "bridge-capture",
        }
    }

    pub const fn default_seeds(self) -> (u64, u64) {
        match self {
            Self::ReturnRace => (0x4e50_4c41_4252_5201, 0x4e50_4c41_4e52_5201),
            Self::Interception => (0x4e50_4c41_4252_5202, 0x4e50_4c41_4e52_5202),
            Self::BaitDisengagement => (0x4e50_4c41_4252_5203, 0x4e50_4c41_4e52_5203),
            Self::DistractedTerritory => (0x4e50_4c41_4252_5204, 0x4e50_4c41_4e52_5204),
            Self::LoopCapture => (0x4e50_4c41_4252_5205, 0x4e50_4c41_4e52_5205),
            Self::BridgeCapture => (0x4e50_4c41_4252_5206, 0x4e50_4c41_4e52_5206),
        }
    }
}

impl fmt::Display for EncounterFixture {
    fn fmt(&self, output: &mut fmt::Formatter<'_>) -> fmt::Result {
        output.write_str(self.label())
    }
}

impl std::str::FromStr for EncounterFixture {
    type Err = String;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        Self::ALL
            .into_iter()
            .find(|fixture| fixture.label() == value)
            .ok_or_else(|| format!("unknown fixture {value:?}"))
    }
}

/// Requested authored profile. Competence/skill remains generated by
/// production roster construction.
#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum PersonalityVariant {
    #[default]
    Baseline,
    Builder,
    Hunter,
    Raider,
}

impl fmt::Display for PersonalityVariant {
    fn fmt(&self, output: &mut fmt::Formatter<'_>) -> fmt::Result {
        output.write_str(match self {
            Self::Baseline => "baseline",
            Self::Builder => "builder",
            Self::Hunter => "hunter",
            Self::Raider => "raider",
        })
    }
}

impl std::str::FromStr for PersonalityVariant {
    type Err = String;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "baseline" => Ok(Self::Baseline),
            "builder" => Ok(Self::Builder),
            "hunter" => Ok(Self::Hunter),
            "raider" => Ok(Self::Raider),
            _ => Err(format!("unknown personality {value:?}")),
        }
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LabVariant {
    pub difficulty: crate::npc::NpcDifficulty,
    pub personality: PersonalityVariant,
    pub trace_capacity: usize,
}

impl Default for LabVariant {
    fn default() -> Self {
        Self {
            difficulty: crate::npc::NpcDifficulty::Normal,
            personality: PersonalityVariant::Baseline,
            trace_capacity: 512,
        }
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LabReplay {
    pub format_version: u32,
    pub setup_version: u32,
    pub fixture: EncounterFixture,
    pub field_seed: u64,
    pub npc_roster_seed: u64,
    pub variant: LabVariant,
    pub board_generation: u64,
    pub setup_hash: u64,
    pub spec: MatchSpec,
    pub human_commands: Vec<SteeringCommand>,
    pub ticks: u64,
    pub expected: Vec<ReplayTick>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReplayTick {
    pub snapshot: ComparableSnapshot,
    pub events: Vec<RecordedEvent>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "kebab-case")]
pub enum RecordedEvent {
    TrailStarted {
        player: u8,
    },
    Capture {
        player: u8,
        area: f32,
        stolen_area: f32,
        loop_fill: bool,
    },
    Death {
        victim: u8,
        killer: Option<u8>,
        cause: String,
    },
    Kill {
        killer: u8,
        total: u32,
        streak: u32,
    },
    Respawn {
        player: u8,
    },
    RankingChanged,
    Go,
    Countdown {
        value: u8,
    },
    Victory {
        winner: u8,
    },
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct LabManeuverStats {
    pub fixed_ticks: u64,
    pub event_counts: BTreeMap<String, u64>,
    pub captures: u64,
    pub deaths: u64,
    pub kills: u64,
    pub trail_starts: u64,
    pub path_length: BTreeMap<u8, f32>,
    pub boundary_contacts: BTreeMap<u8, u64>,
    pub max_steering_error: BTreeMap<u8, f32>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LabDecisionSample {
    pub tick: u64,
    pub npc: u8,
    /// Human-readable compatibility label. Acceptance uses explicit fields.
    pub action: String,
    pub reason: String,
    pub tactic_kind: Option<String>,
    pub tactic_detail: Option<String>,
    pub tactic_phase: Option<String>,
    pub tactic_sequence: u64,
    pub tactic_started_tick: Option<u64>,
    pub tactic_transition: bool,
    pub previous_tactic_kind: Option<String>,
    pub position: [f32; 2],
    pub heading: [f32; 2],
    pub steering_error: f32,
    pub safety_override: bool,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct LabTrace {
    pub decisions: Vec<LabDecisionSample>,
    pub trajectories: BTreeMap<u8, Vec<[f32; 2]>>,
    /// Fixed ticks for each trajectory sample.
    pub trajectory_ticks: BTreeMap<u8, Vec<u64>>,
    /// Ownership sampled at the same ticks as `trajectories`.
    pub trajectory_ownership: BTreeMap<u8, Vec<bool>>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LabAcceptanceCheck {
    pub name: String,
    pub passed: bool,
    pub requirement: String,
    pub observed: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct LabAcceptance {
    pub passed: bool,
    pub checks: Vec<LabAcceptanceCheck>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LabReport {
    pub format_version: u32,
    pub setup_version: u32,
    pub fixture: EncounterFixture,
    pub field_seed: u64,
    pub npc_roster_seed: u64,
    pub variant: LabVariant,
    pub board_generation: u64,
    pub setup_hash: u64,
    pub final_snapshot: ComparableSnapshot,
    pub stats: LabManeuverStats,
    pub trace: LabTrace,
    pub acceptance: LabAcceptance,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LabArtifact {
    pub replay: LabReplay,
    pub report: LabReport,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum LabError {
    InvalidTicks,
    InvalidFixture(String),
    InvalidSetup(String),
    Command(String),
    Serialization(String),
    Io(String),
}

impl fmt::Display for LabError {
    fn fmt(&self, output: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(output, "{self:?}")
    }
}

impl std::error::Error for LabError {}
